"""
llm_foundry/stage3_scaling/isoflops.py — IsoFLOPs Curve Calculator

This module provides utilities for computing IsoFLOPs curves following the
Chinchilla scaling laws (Hoffmann et al., 2022).

Key formulas:
    - FLOPs ≈ 6 * N * D (N=parameters, D=tokens)
    - Chinchilla optimal: N_opt ∝ C^0.5, D_opt ∝ C^0.5

Classes:
    IsoFLOPsConfig: Configuration for IsoFLOPs calculations

Functions:
    compute_flops: Calculate training FLOPs for a given model size and token count
    generate_isoflop_curves: Generate (N, D) configurations for fixed FLOPs budgets
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any

import numpy as np


# ─────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────

@dataclass
class IsoFLOPsConfig:
    """
    Configuration for IsoFLOPs curve calculations.

    Attributes:
        compute_budgets: List of FLOPs budgets to analyze (e.g., [1e18, 1e19, 1e20])
        n_points_per_budget: Number of (N, D) points to generate per budget
        n_range: Tuple of (min_n, max_n) for parameter sweep in log space
        flops_per_token_per_param: FLOPs multiplier (default 6.0 for forward+backward)
    """
    compute_budgets: list[float] = field(default_factory=lambda: [1e18, 1e19, 1e20, 1e21])
    n_points_per_budget: int = 10
    n_range: tuple[float, float] = (1e6, 1e12)  # (min_params, max_params)
    flops_per_token_per_param: float = 6.0  # 2 for forward + 4 for backward

    def to_dict(self) -> dict[str, Any]:
        """Convert config to dictionary."""
        return {
            "compute_budgets": self.compute_budgets,
            "n_points_per_budget": self.n_points_per_budget,
            "n_range": self.n_range,
            "flops_per_token_per_param": self.flops_per_token_per_param,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> IsoFLOPsConfig:
        """Create config from dictionary."""
        return cls(
            compute_budgets=d.get("compute_budgets", [1e18, 1e19, 1e20, 1e21]),
            n_points_per_budget=d.get("n_points_per_budget", 10),
            n_range=tuple(d.get("n_range", [1e6, 1e12])),
            flops_per_token_per_param=d.get("flops_per_token_per_param", 6.0),
        )

    @classmethod
    def from_json(cls, path: str) -> IsoFLOPsConfig:
        """Load config from JSON file."""
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        return cls.from_dict(data)


# ─────────────────────────────────────────
# Core Functions
# ─────────────────────────────────────────

def compute_flops(n_params: float, n_tokens: float, multiplier: float = 6.0) -> float:
    """
    Calculate total training FLOPs for a given model size and token count.

    Formula: FLOPs = multiplier * N * D

    The default multiplier is 6.0, which accounts for:
        - Forward pass: 2 * N * D FLOPs
        - Backward pass: 4 * N * D FLOPs (gradients + activation gradients)
        - Total: 6 * N * D FLOPs

    Args:
        n_params: Number of model parameters (N)
        n_tokens: Number of training tokens (D)
        multiplier: FLOPs multiplier (default 6.0)

    Returns:
        Total training FLOPs (C)

    Example:
        >>> compute_flops(1e9, 1e9)  # 1B params, 1B tokens
        6e+18
    """
    return multiplier * n_params * n_tokens


def generate_isoflop_curves(
    config: IsoFLOPsConfig | None = None,
    compute_budgets: list[float] | None = None,
) -> dict[float, list[dict[str, float]]]:
    """
    Generate (N, D) configurations for fixed FLOPs budgets.

    For each compute budget C, generates multiple (N, D) pairs that satisfy:
        C = 6 * N * D

    The configurations are generated by sweeping N (parameters) in log space
    and computing D = C / (6 * N).

    Args:
        config: IsoFLOPsConfig instance (uses defaults if None)
        compute_budgets: Override list of compute budgets (uses config.compute_budgets if None)

    Returns:
        Dictionary mapping compute budget to list of (N, D) configurations:
        {
            1e18: [
                {"n_params": 1e6, "n_tokens": 1.67e11, "flops": 1e18},
                {"n_params": 3.16e6, "n_tokens": 5.27e10, "flops": 1e18},
                ...
            ],
            1e19: [...],
            ...
        }

    Example:
        >>> config = IsoFLOPsConfig(compute_budgets=[1e18], n_points_per_budget=5)
        >>> curves = generate_isoflop_curves(config)
        >>> len(curves[1e18])
        5
    """
    if config is None:
        config = IsoFLOPsConfig()

    budgets = compute_budgets if compute_budgets is not None else config.compute_budgets
    n_min, n_max = config.n_range
    multiplier = config.flops_per_token_per_param

    curves: dict[float, list[dict[str, float]]] = {}

    for C in budgets:
        # For this compute budget, generate N values in log space
        # such that D = C / (6 * N) stays within reasonable bounds

        # Compute valid N range for this C
        # D must be at least 1 token, so N <= C / 6
        # D should be at most C / (6 * n_min) to avoid tiny N
        n_upper = min(n_max, C / (multiplier * 1.0))  # At least 1 token
        n_lower = max(n_min, C / (multiplier * 1e13))  # At most 1e13 tokens (generous upper bound)

        # Generate N values in log space
        log_n_values = np.linspace(np.log10(n_lower), np.log10(n_upper), config.n_points_per_budget)
        n_values = 10 ** log_n_values

        points = []
        for N in n_values:
            D = C / (multiplier * N)
            points.append({
                "n_params": float(N),
                "n_tokens": float(D),
                "flops": float(C),
            })

        curves[float(C)] = points

    return curves


def find_optimal_nd_for_compute(
    compute_budget: float,
    loss_data: list[dict[str, float]],
    multiplier: float = 6.0,
) -> dict[str, float] | None:
    """
    Find the optimal (N, D) configuration for a given compute budget.

    Given experimental data with different (N, D) pairs and their losses,
    finds the configuration with the minimum loss that matches the compute budget.

    Args:
        compute_budget: Target compute budget in FLOPs (C)
        loss_data: List of experimental results, each containing:
            - n_params: Model parameters
            - n_tokens: Training tokens
            - loss: Validation loss
        multiplier: FLOPs multiplier (default 6.0)

    Returns:
        Dictionary with optimal configuration, or None if no matching data:
        {
            "n_params": float,
            "n_tokens": float,
            "loss": float,
            "compute": float,
        }
    """
    # Group by compute budget (with tolerance for floating point)
    matching_points = []
    for point in loss_data:
        n_params = point["n_params"]
        n_tokens = point["n_tokens"]
        point_compute = compute_flops(n_params, n_tokens, multiplier)

        # Check if this point matches the target compute budget
        # Use relative tolerance of 10% for compute budget matching
        if abs(point_compute - compute_budget) / compute_budget < 0.1:
            matching_points.append({
                "n_params": n_params,
                "n_tokens": n_tokens,
                "loss": point["loss"],
                "compute": point_compute,
            })

    if not matching_points:
        return None

    # Return the point with minimum loss
    return min(matching_points, key=lambda x: x["loss"])


def fit_power_law(
    compute_values: np.ndarray,
    target_values: np.ndarray,
) -> tuple[float, float]:
    """
    Fit a power law y = A * C^b using log-space linear regression.

    Args:
        compute_values: Array of compute budgets (C)
        target_values: Array of target values (N or D)

    Returns:
        Tuple of (factor_A, exponent_b) where y = A * C^b

    Example:
        >>> C = np.array([1e18, 1e19, 1e20])
        >>> N = np.array([1e9, 3.16e9, 1e10])  # N ∝ C^0.5
        >>> A, b = fit_power_law(C, N)
        >>> print(f"N = {A:.2e} * C^{b:.3f}")
    """
    log_C = np.log(compute_values)
    log_y = np.log(target_values)

    # Linear regression: log(y) = b * log(C) + log(A)
    # Using least squares
    A_matrix = np.vstack([log_C, np.ones(len(log_C))]).T
    b, log_A = np.linalg.lstsq(A_matrix, log_y, rcond=None)[0]

    factor_A = np.exp(log_A)
    exponent_b = b

    return float(factor_A), float(exponent_b)


def predict_optimal_size(
    compute_budget: float,
    factor: float,
    exponent: float,
) -> float:
    """
    Predict optimal model size or token count for a given compute budget.

    Formula: y = factor * C^exponent

    Args:
        compute_budget: Target compute budget (C)
        factor: Power law factor (A)
        exponent: Power law exponent (b)

    Returns:
        Predicted optimal value (N_opt or D_opt)

    Example:
        >>> # Chinchilla: N_opt ≈ 0.1 * C^0.5
        >>> N_opt = predict_optimal_size(1e21, 0.1, 0.5)
        >>> print(f"Optimal params for 1e21 FLOPs: {N_opt:.2e}")
    """
    return factor * (compute_budget ** exponent)


# ─────────────────────────────────────────
# Convenience Functions
# ─────────────────────────────────────────

def get_chinchilla_optimal(
    compute_budget: float,
    chinchilla_factor: float = 0.1,  # Approximate from Hoffmann et al.
) -> tuple[float, float]:
    """
    Get Chinchilla-optimal model size and token count for a compute budget.

    Following Hoffmann et al. (2022), the optimal configurations follow:
        N_opt ≈ 0.1 * C^0.5
        D_opt ≈ 10 * C^0.5

    where C is in FLOPs.

    Args:
        compute_budget: Target compute budget in FLOPs
        chinchilla_factor: Scaling factor (default 0.1 for N_opt)

    Returns:
        Tuple of (n_params_optimal, n_tokens_optimal)

    Example:
        >>> N, D = get_chinchilla_optimal(1e21)  # GPT-4 scale
        >>> print(f"Optimal: {N:.2e} params, {D:.2e} tokens")
    """
    C = compute_budget
    N_opt = chinchilla_factor * (C ** 0.5)
    # From C = 6 * N * D, we get D = C / (6 * N)
    D_opt = C / (6.0 * N_opt)
    return N_opt, D_opt


def estimate_training_cost(
    n_params: float,
    n_tokens: float,
    hardware_flops_per_sec: float = 1e12,  # 1 TFLOPS
    hardware_cost_per_hour: float = 2.0,   # $2/hour
) -> dict[str, float]:
    """
    Estimate training time and cost for a given configuration.

    Args:
        n_params: Number of model parameters
        n_tokens: Number of training tokens
        hardware_flops_per_sec: Hardware FLOPs per second
        hardware_cost_per_hour: Hardware cost per hour in dollars

    Returns:
        Dictionary with training estimates:
        {
            "total_flops": float,
            "training_seconds": float,
            "training_hours": float,
            "training_days": float,
            "estimated_cost_usd": float,
        }
    """
    total_flops = compute_flops(n_params, n_tokens)
    training_seconds = total_flops / hardware_flops_per_sec
    training_hours = training_seconds / 3600
    training_days = training_hours / 24
    estimated_cost = training_hours * hardware_cost_per_hour

    return {
        "total_flops": total_flops,
        "training_seconds": training_seconds,
        "training_hours": training_hours,
        "training_days": training_days,
        "estimated_cost_usd": estimated_cost,
    }


def format_flops(flops: float) -> str:
    """
    Format FLOPs value in human-readable form.

    Args:
        flops: FLOPs value

    Returns:
        Human-readable string (e.g., "1.0e18", "1.0 PFLOPs")

    Example:
        >>> format_flops(6e18)
        '6.0e18 (6.0 EFLOPs)'
    """
    units = [
        (1e24, "YFLOPs"),  # Yotta
        (1e21, "ZFLOPs"),  # Zetta
        (1e18, "EFLOPs"),  # Exa
        (1e15, "PFLOPs"),  # Peta
        (1e12, "TFLOPs"),  # Tera
        (1e9, "GFLOPs"),   # Giga
        (1e6, "MFLOPs"),   # Mega
    ]

    for factor, unit in units:
        if flops >= factor:
            return f"{flops:.1e} ({flops/factor:.1f} {unit})"

    return f"{flops:.1e} FLOPs"
